--TEST--
simdjson_encode() escape long
--FILE--
<?php
for ($i = 0; $i < 127; $i++) {
    echo "$i: ";
    $dummyText = "dummy test that is long enough";
    $original = json_encode(chr($i) . $dummyText, JSON_UNESCAPED_LINE_TERMINATORS | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    $simdjson = simdjson_encode(chr($i) . $dummyText);
    if ($original !== $simdjson) {
        echo "Different!!! Original: $original, simdjson $simdjson\n";
    }
    var_dump($simdjson);
}
?>
--EXPECT--
0: string(38) ""\u0000dummy test that is long enough""
1: string(38) ""\u0001dummy test that is long enough""
2: string(38) ""\u0002dummy test that is long enough""
3: string(38) ""\u0003dummy test that is long enough""
4: string(38) ""\u0004dummy test that is long enough""
5: string(38) ""\u0005dummy test that is long enough""
6: string(38) ""\u0006dummy test that is long enough""
7: string(38) ""\u0007dummy test that is long enough""
8: string(34) ""\bdummy test that is long enough""
9: string(34) ""\tdummy test that is long enough""
10: string(34) ""\ndummy test that is long enough""
11: string(38) ""\u000bdummy test that is long enough""
12: string(34) ""\fdummy test that is long enough""
13: string(34) ""\rdummy test that is long enough""
14: string(38) ""\u000edummy test that is long enough""
15: string(38) ""\u000fdummy test that is long enough""
16: string(38) ""\u0010dummy test that is long enough""
17: string(38) ""\u0011dummy test that is long enough""
18: string(38) ""\u0012dummy test that is long enough""
19: string(38) ""\u0013dummy test that is long enough""
20: string(38) ""\u0014dummy test that is long enough""
21: string(38) ""\u0015dummy test that is long enough""
22: string(38) ""\u0016dummy test that is long enough""
23: string(38) ""\u0017dummy test that is long enough""
24: string(38) ""\u0018dummy test that is long enough""
25: string(38) ""\u0019dummy test that is long enough""
26: string(38) ""\u001adummy test that is long enough""
27: string(38) ""\u001bdummy test that is long enough""
28: string(38) ""\u001cdummy test that is long enough""
29: string(38) ""\u001ddummy test that is long enough""
30: string(38) ""\u001edummy test that is long enough""
31: string(38) ""\u001fdummy test that is long enough""
32: string(33) "" dummy test that is long enough""
33: string(33) ""!dummy test that is long enough""
34: string(34) ""\"dummy test that is long enough""
35: string(33) ""#dummy test that is long enough""
36: string(33) ""$dummy test that is long enough""
37: string(33) ""%dummy test that is long enough""
38: string(33) ""&dummy test that is long enough""
39: string(33) ""'dummy test that is long enough""
40: string(33) ""(dummy test that is long enough""
41: string(33) "")dummy test that is long enough""
42: string(33) ""*dummy test that is long enough""
43: string(33) ""+dummy test that is long enough""
44: string(33) "",dummy test that is long enough""
45: string(33) ""-dummy test that is long enough""
46: string(33) "".dummy test that is long enough""
47: string(33) ""/dummy test that is long enough""
48: string(33) ""0dummy test that is long enough""
49: string(33) ""1dummy test that is long enough""
50: string(33) ""2dummy test that is long enough""
51: string(33) ""3dummy test that is long enough""
52: string(33) ""4dummy test that is long enough""
53: string(33) ""5dummy test that is long enough""
54: string(33) ""6dummy test that is long enough""
55: string(33) ""7dummy test that is long enough""
56: string(33) ""8dummy test that is long enough""
57: string(33) ""9dummy test that is long enough""
58: string(33) "":dummy test that is long enough""
59: string(33) "";dummy test that is long enough""
60: string(33) ""<dummy test that is long enough""
61: string(33) ""=dummy test that is long enough""
62: string(33) "">dummy test that is long enough""
63: string(33) ""?dummy test that is long enough""
64: string(33) ""@dummy test that is long enough""
65: string(33) ""Adummy test that is long enough""
66: string(33) ""Bdummy test that is long enough""
67: string(33) ""Cdummy test that is long enough""
68: string(33) ""Ddummy test that is long enough""
69: string(33) ""Edummy test that is long enough""
70: string(33) ""Fdummy test that is long enough""
71: string(33) ""Gdummy test that is long enough""
72: string(33) ""Hdummy test that is long enough""
73: string(33) ""Idummy test that is long enough""
74: string(33) ""Jdummy test that is long enough""
75: string(33) ""Kdummy test that is long enough""
76: string(33) ""Ldummy test that is long enough""
77: string(33) ""Mdummy test that is long enough""
78: string(33) ""Ndummy test that is long enough""
79: string(33) ""Odummy test that is long enough""
80: string(33) ""Pdummy test that is long enough""
81: string(33) ""Qdummy test that is long enough""
82: string(33) ""Rdummy test that is long enough""
83: string(33) ""Sdummy test that is long enough""
84: string(33) ""Tdummy test that is long enough""
85: string(33) ""Udummy test that is long enough""
86: string(33) ""Vdummy test that is long enough""
87: string(33) ""Wdummy test that is long enough""
88: string(33) ""Xdummy test that is long enough""
89: string(33) ""Ydummy test that is long enough""
90: string(33) ""Zdummy test that is long enough""
91: string(33) ""[dummy test that is long enough""
92: string(34) ""\\dummy test that is long enough""
93: string(33) ""]dummy test that is long enough""
94: string(33) ""^dummy test that is long enough""
95: string(33) ""_dummy test that is long enough""
96: string(33) ""`dummy test that is long enough""
97: string(33) ""adummy test that is long enough""
98: string(33) ""bdummy test that is long enough""
99: string(33) ""cdummy test that is long enough""
100: string(33) ""ddummy test that is long enough""
101: string(33) ""edummy test that is long enough""
102: string(33) ""fdummy test that is long enough""
103: string(33) ""gdummy test that is long enough""
104: string(33) ""hdummy test that is long enough""
105: string(33) ""idummy test that is long enough""
106: string(33) ""jdummy test that is long enough""
107: string(33) ""kdummy test that is long enough""
108: string(33) ""ldummy test that is long enough""
109: string(33) ""mdummy test that is long enough""
110: string(33) ""ndummy test that is long enough""
111: string(33) ""odummy test that is long enough""
112: string(33) ""pdummy test that is long enough""
113: string(33) ""qdummy test that is long enough""
114: string(33) ""rdummy test that is long enough""
115: string(33) ""sdummy test that is long enough""
116: string(33) ""tdummy test that is long enough""
117: string(33) ""udummy test that is long enough""
118: string(33) ""vdummy test that is long enough""
119: string(33) ""wdummy test that is long enough""
120: string(33) ""xdummy test that is long enough""
121: string(33) ""ydummy test that is long enough""
122: string(33) ""zdummy test that is long enough""
123: string(33) ""{dummy test that is long enough""
124: string(33) ""|dummy test that is long enough""
125: string(33) ""}dummy test that is long enough""
126: string(33) ""~dummy test that is long enough""